title:            Matthias Mullie
tagline:          'Software engineer'
description:      'Matthias Mullie, software engineer'
url:              https://www.mullie.eu
baseurl:          ""
image:            public/logo_300.png
enforce_ssl:      www.mullie.eu

author:
  name:           'Matthias Mullie'
  twitter:        matthiasmullie

markdown:         kramdown
theme:            minima
paginate:         5
paginate_path:    "/page:num/"

version:          1.0.0

github:
  repo:           https://github.com/matthiasmullie/mullie.eu

permalink:        /:title/

gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-archives
  - jekyll-sitemap

jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: tag
  parmalinks:
    tag: '/tag/:name'

# Titles of posts to be displayed in "top posts" widget
top_posts:       ["Geographic searches within a certain distance", "Regular expressions for pros", "Measuring software complexity"]
